### ISSUE TITLE
Solved: Question: DepthBasics.cpp 

### ISSUE THREAD

**Issue by lalaphoon** [bitcraze/kinect-detector-windows#1]
Hi, I'm not too professional on this. What is '0LL' at line 58?
`m_nNextStatusTime(0LL),`

Thank you!

**Comment by lalaphoon** [comment]
Sorry Sorry I searched...It's
`0LL // ending with 'LL' makes it long long`

**Comment by ataffanel** [comment]
Yes it makes it a 64bit integer constant.
